# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'landing.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 640)
        MainWindow.setMinimumSize(QtCore.QSize(640, 640))
        MainWindow.setMaximumSize(QtCore.QSize(640, 640))
        MainWindow.setStyleSheet("QWidget#centralwidget {\n"
"    border: 3px solid #001A3D;\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 0px 15px #001A3D;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {\n"
"    background-image: url(\"bg.jpg\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 170, 151, 31))
        self.label.setStyleSheet("color: #ffd86b;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 260, 201, 21))
        self.label_2.setStyleSheet("color: #ffd86b;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 270, 55, 16))
        self.label_4.setStyleSheet("color: #ffd86b;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(120, 120, 101, 51))
        self.label_6.setStyleSheet("color: #ffd86b;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(120, 220, 151, 21))
        self.label_7.setStyleSheet("color: #ffd86b;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"")
        self.label_7.setObjectName("label_7")
        self.input_gravity = QtWidgets.QSpinBox(self.centralwidget)
        self.input_gravity.setGeometry(QtCore.QRect(460, 130, 61, 31))
        self.input_gravity.setStyleSheet("QSpinBox, QComboBox {\n"
"    background-color: rgba(20,20,20,180);\n"
"    color: white;\n"
"    border: 2px solid #00AFFF;\n"
"    border-radius: 6px;\n"
"    padding: 2px;\n"
"}\n"
"")
        self.input_gravity.setObjectName("input_gravity")
        self.btn_predict = QtWidgets.QPushButton(self.centralwidget)
        self.btn_predict.setGeometry(QtCore.QRect(250, 430, 121, 41))
        self.btn_predict.setStyleSheet("QPushButton#btn_predict {\n"
"    background-color: transparent;\n"
"    color: #00AFFF;\n"
"    border: 2px solid #00AFFF;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-family: Orbitron;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#btn_predict:hover {\n"
"    box-shadow: 0px 0px 12px #00AFFF;\n"
"    background-color: rgba(0, 170, 255, 40);\n"
"}\n"
"\n"
"QPushButton#btn_predict:pressed {\n"
"    color: black;\n"
"    background-color: #00AFFF;\n"
"}\n"
"")
        self.btn_predict.setObjectName("btn_predict")
        self.input_radiation = QtWidgets.QSpinBox(self.centralwidget)
        self.input_radiation.setGeometry(QtCore.QRect(460, 220, 61, 31))
        self.input_radiation.setStyleSheet("QSpinBox, QComboBox {\n"
"    background-color: rgba(20,20,20,180);\n"
"    color: white;\n"
"    border: 2px solid #00AFFF;\n"
"    border-radius: 6px;\n"
"    padding: 2px;\n"
"}\n"
"")
        self.input_radiation.setObjectName("input_radiation")
        self.input_temperature = QtWidgets.QSpinBox(self.centralwidget)
        self.input_temperature.setGeometry(QtCore.QRect(460, 170, 61, 31))
        self.input_temperature.setStyleSheet("QSpinBox, QComboBox {\n"
"    background-color: rgba(20,20,20,180);\n"
"    color: white;\n"
"    border: 2px solid #00AFFF;\n"
"    border-radius: 6px;\n"
"    padding: 2px;\n"
"}\n"
"")
        self.input_temperature.setObjectName("input_temperature")
        self.combo_water = QtWidgets.QComboBox(self.centralwidget)
        self.combo_water.setGeometry(QtCore.QRect(440, 260, 81, 31))
        self.combo_water.setStyleSheet("QSpinBox, QComboBox {\n"
"    background-color: rgba(20,20,20,180);\n"
"    color: white;\n"
"    border: 2px solid #00AFFF;\n"
"    border-radius: 6px;\n"
"    padding: 2px;\n"
"}\n"
"")
        self.combo_water.setObjectName("combo_water")
        self.combo_water.addItem("")
        self.combo_water.addItem("")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(110, 30, 421, 20))
        self.label_title.setStyleSheet("color: #00C8FF;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"")
        self.label_title.setObjectName("label_title")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(120, 300, 231, 31))
        self.label_8.setStyleSheet("color: #ffd86b;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(120, 340, 231, 31))
        self.label_9.setStyleSheet("color: #ffd86b;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(120, 380, 231, 31))
        self.label_10.setStyleSheet("color: #ffd86b;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"")
        self.label_10.setObjectName("label_10")
        self.input_wind = QtWidgets.QSpinBox(self.centralwidget)
        self.input_wind.setGeometry(QtCore.QRect(460, 300, 61, 31))
        self.input_wind.setStyleSheet("QSpinBox, QComboBox {\n"
"    background-color: rgba(20,20,20,180);\n"
"    color: white;\n"
"    border: 2px solid #00AFFF;\n"
"    border-radius: 6px;\n"
"    padding: 2px;\n"
"}\n"
"")
        self.input_wind.setObjectName("input_wind")
        self.input_toxicity = QtWidgets.QSpinBox(self.centralwidget)
        self.input_toxicity.setGeometry(QtCore.QRect(460, 340, 61, 31))
        self.input_toxicity.setStyleSheet("QSpinBox, QComboBox {\n"
"    background-color: rgba(20,20,20,180);\n"
"    color: white;\n"
"    border: 2px solid #00AFFF;\n"
"    border-radius: 6px;\n"
"    padding: 2px;\n"
"}\n"
"")
        self.input_toxicity.setObjectName("input_toxicity")
        self.combo_terrain = QtWidgets.QComboBox(self.centralwidget)
        self.combo_terrain.setGeometry(QtCore.QRect(440, 380, 81, 31))
        self.combo_terrain.setStyleSheet("QSpinBox, QComboBox {\n"
"    background-color: rgba(20,20,20,180);\n"
"    color: white;\n"
"    border: 2px solid #00AFFF;\n"
"    border-radius: 6px;\n"
"    padding: 2px;\n"
"}\n"
"")
        self.combo_terrain.setObjectName("combo_terrain")
        self.combo_terrain.addItem("")
        self.combo_terrain.addItem("")
        self.combo_terrain.addItem("")
        self.combo_terrain.addItem("")
        self.combo_terrain.addItem("")
        self.combo_terrain.addItem("")
        self.combo_terrain.addItem("")
        self.combo_terrain.addItem("")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(120, 90, 231, 31))
        self.label_11.setStyleSheet("color: #ffd86b;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"")
        self.label_11.setObjectName("label_11")
        self.input_atmosphere = QtWidgets.QSpinBox(self.centralwidget)
        self.input_atmosphere.setGeometry(QtCore.QRect(460, 90, 61, 31))
        self.input_atmosphere.setStyleSheet("QSpinBox, QComboBox {\n"
"    background-color: rgba(20,20,20,180);\n"
"    color: white;\n"
"    border: 2px solid #00AFFF;\n"
"    border-radius: 6px;\n"
"    padding: 2px;\n"
"}\n"
"")
        self.input_atmosphere.setObjectName("input_atmosphere")
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset.setGeometry(QtCore.QRect(260, 500, 93, 28))
        self.btn_reset.setStyleSheet("QPushButton#btn_predict {\n"
"    background-color: transparent;\n"
"    color: #00AFFF;\n"
"    border: 2px solid #00AFFF;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-family: Orbitron;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#btn_predict:hover {\n"
"    box-shadow: 0px 0px 12px #00AFFF;\n"
"    background-color: rgba(0, 170, 255, 40);\n"
"}\n"
"\n"
"QPushButton#btn_predict:pressed {\n"
"    color: black;\n"
"    background-color: #00AFFF;\n"
"}\n"
"")
        self.btn_reset.setObjectName("btn_reset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Temperature"))
        self.label_2.setText(_translate("MainWindow", "Water Present"))
        self.label_6.setText(_translate("MainWindow", "Gravity"))
        self.label_7.setText(_translate("MainWindow", "Radiation"))
        self.btn_predict.setText(_translate("MainWindow", "Predict"))
        self.combo_water.setItemText(0, _translate("MainWindow", "Present"))
        self.combo_water.setItemText(1, _translate("MainWindow", "Not Present"))
        self.label_title.setText(_translate("MainWindow", "AI CO-PILOT SAFETY PREDICTOR 1.2"))
        self.label_8.setText(_translate("MainWindow", "Wind"))
        self.label_9.setText(_translate("MainWindow", "Toxicity "))
        self.label_10.setText(_translate("MainWindow", "Terrain"))
        self.combo_terrain.setItemText(0, _translate("MainWindow", "Canyon"))
        self.combo_terrain.setItemText(1, _translate("MainWindow", "Dessert"))
        self.combo_terrain.setItemText(2, _translate("MainWindow", "Forest"))
        self.combo_terrain.setItemText(3, _translate("MainWindow", "Icy"))
        self.combo_terrain.setItemText(4, _translate("MainWindow", "Plains"))
        self.combo_terrain.setItemText(5, _translate("MainWindow", "Rocky"))
        self.combo_terrain.setItemText(6, _translate("MainWindow", "Swamp"))
        self.combo_terrain.setItemText(7, _translate("MainWindow", "Volcanic"))
        self.label_11.setText(_translate("MainWindow", "Atmosphere"))
        self.btn_reset.setText(_translate("MainWindow", "Reset"))
